#predict_len 96
!python run.py 
    --is_training 1 
    --model LGT 
    --model_id lgt_test 
    --ma_type dema 
    --data custom 
    --learning_rate 0.005 
    --data_path traffic.csv 
    --seq_len 96 
    --pred_len 96 
    --enc_in 862 
    --batch_size 32 
    --d_model 32 
    --dropout 0 
    --num_layers 2 
    --stride 12 
    --train_epochs 200

#predict_len 192
!python run.py
    --is_training 1 
    --model LGT 
    --model_id lgt_test 
    --ma_type dema 
    --data custom 
    --learning_rate 0.005 
    --data_path traffic.csv 
    --seq_len 96 
    --pred_len 192 
    --enc_in 862 
    --batch_size 32 
    --d_model 32 
    --dropout 0 
    --num_layers 3 
    --stride 12 
    --train_epochs 200

#predict_len 336
!python run.py 
    --is_training 1 
    --model LGT 
    --model_id lgt_test 
    --ma_type dema 
    --data custom 
    --learning_rate 0.005 
    --data_path traffic.csv 
    --seq_len 96 
    --pred_len 336 
    --enc_in 862 
    --batch_size 32 
    --d_model 32 
    --dropout 0 
    --num_layers 3 
    --stride 12 
    --train_epochs 200

#predict_len 720
!python run.py 
    --is_training 1 
    --model LGT 
    --model_id lgt_test 
    --ma_type dema 
    --data custom 
    --learning_rate 0.005 
    --data_path traffic.csv 
    --seq_len 96 
    --pred_len 720 
    --enc_in 862 
    --batch_size 32 
    --d_model 32 
    --dropout 0.2
    --num_layers 3
    --stride 12 
    --train_epochs 200